---
- name: Hot-add Disk to OpenShift Virtual Machine
  hosts: "{{ vm_name }}"
  gather_facts: false
  connection: local

  vars:
    # Optional variables with defaults (non-recursive)
    _disk_bus: "scsi"
    _storage_class: "{{ (storage_class | first) if (storage_class is defined and storage_class is iterable and storage_class is not string) else (storage_class | default('ocs-storagecluster-ceph-rbd')) }}"
    _access_mode: "{{ access_mode | default('ReadWriteMany') }}"
    _volume_mode: "{{ volume_mode | default('Block') }}"
    _wait_for_datavolume: "{{ wait_for_datavolume | default(true) }}"
    _datavolume_timeout: "{{ datavolume_timeout | default(300) }}"
    _datavolume_retry_delay: "{{ datavolume_retry_delay | default(10) }}"

  tasks:
    - name: Generate disk name if not provided
      ansible.builtin.set_fact:
        _disk_name: "{{ disk_name if (disk_name is defined and disk_name | length > 0) else 'disk-' + lookup('pipe', 'date +%s') }}"
      delegate_to: localhost
      run_once: true

    - name: Ensure disk_bus is a string (override vars section for AAP)
      ansible.builtin.set_fact:
        _disk_bus: "scsi"
      delegate_to: localhost
      run_once: true

    - name: Validate required survey variables
      ansible.builtin.assert:
        that:
          - vm_name is defined
          - vm_name | length > 0
          - vm_namespace is defined
          - vm_namespace | length > 0
          - disk_size is defined
          - disk_size | length > 0
        fail_msg: "Required variables missing. Survey must provide: vm_name, vm_namespace, and disk_size"
        success_msg: "All required survey variables validated"
      delegate_to: localhost
      run_once: true

    - name: Display disk addition plan
      ansible.builtin.debug:
        msg:
          - "=========================================="
          - "Hot-Add Disk Operation"
          - "=========================================="
          - "VM Name: {{ vm_name }}"
          - "Namespace: {{ vm_namespace }}"
          - "New Disk Name: {{ _disk_name }}"
          - "Disk Size: {{ disk_size }}"
          - "Storage Class: {{ _storage_class }}"
          - "Disk Bus Type: {{ _disk_bus }}"
          - "=========================================="
      delegate_to: localhost
      run_once: true

    - name: Check if VM exists
      kubernetes.core.k8s_info:
        api_version: kubevirt.io/v1
        kind: VirtualMachine
        name: "{{ vm_name }}"
        namespace: "{{ vm_namespace }}"
      register: vm_check
      failed_when: vm_check.resources | length == 0
      delegate_to: localhost
      run_once: true

    - name: Display VM status
      ansible.builtin.debug:
        msg: "✓ VM '{{ vm_name }}' found in namespace '{{ vm_namespace }}'"
      delegate_to: localhost
      run_once: true

    - name: Check if disk already exists in VM
      ansible.builtin.set_fact:
        existing_volumes: "{{ vm_check.resources[0].spec.template.spec.volumes | default([]) }}"
        existing_disks: "{{ vm_check.resources[0].spec.template.spec.domain.devices.disks | default([]) }}"
      delegate_to: localhost
      run_once: true

    - name: Verify disk name is unique
      ansible.builtin.assert:
        that:
          - _disk_name not in (existing_volumes | map(attribute='name') | list)
        fail_msg: "Disk with name '{{ _disk_name }}' already exists in VM '{{ vm_name }}'"
        success_msg: "Disk name '{{ _disk_name }}' is unique and available"
      delegate_to: localhost
      run_once: true

    - name: Create DataVolume for hot-plug disk
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: cdi.kubevirt.io/v1beta1
          kind: DataVolume
          metadata:
            name: "{{ _disk_name }}"
            namespace: "{{ vm_namespace }}"
            labels:
              app.kubernetes.io/managed-by: ansible
              vm.kubevirt.io/name: "{{ vm_name }}"
              disk.vm.kubevirt.io/type: hot-plugged
            annotations:
              description: "Hot-plugged disk for VM {{ vm_name }}"
              created-by: "ansible-automation-platform"
              created-at: "{{ lookup('pipe', 'date -u +%Y-%m-%dT%H:%M:%SZ') }}"
              disk-size: "{{ disk_size }}"
          spec:
            source:
              blank: {}
            storage:
              accessModes:
                - "{{ _access_mode }}"
              resources:
                requests:
                  storage: "{{ disk_size }}"
              storageClassName: "{{ _storage_class }}"
              volumeMode: "{{ _volume_mode }}"
      register: datavolume_create
      delegate_to: localhost
      run_once: true

    - name: Display DataVolume creation status
      ansible.builtin.debug:
        msg: "DataVolume '{{ _disk_name }}' created successfully"
      when: datavolume_create is succeeded
      delegate_to: localhost
      run_once: true

    - name: Wait for DataVolume to be ready
      kubernetes.core.k8s_info:
        api_version: cdi.kubevirt.io/v1beta1
        kind: DataVolume
        name: "{{ _disk_name }}"
        namespace: "{{ vm_namespace }}"
      register: dv_status
      until:
        - dv_status.resources | length > 0
        - dv_status.resources[0].status.phase is defined
        - dv_status.resources[0].status.phase == "Succeeded"
      retries: "{{ (_datavolume_timeout | int / _datavolume_retry_delay | int) | int }}"
      delay: "{{ _datavolume_retry_delay }}"
      when: _wait_for_datavolume | bool
      delegate_to: localhost
      run_once: true

    - name: Display DataVolume ready status
      ansible.builtin.debug:
        msg:
          - "DataVolume '{{ _disk_name }}' is ready"
          - "Phase: {{ dv_status.resources[0].status.phase }}"
          - "Progress: {{ dv_status.resources[0].status.progress | default('100%') }}"
      when:
        - _wait_for_datavolume | bool
        - dv_status.resources | length > 0
      delegate_to: localhost
      run_once: true

    - name: Get Kubernetes API endpoint
      ansible.builtin.set_fact:
        k8s_api_endpoint: "{{ lookup('env', 'K8S_AUTH_HOST') | default(lookup('env', 'KUBERNETES_SERVICE_HOST') | default('api.cluster.local', true), true) }}"
      delegate_to: localhost
      run_once: true

    - name: Hot-plug disk to VM using addvolume API
      ansible.builtin.uri:
        url: "{{ k8s_api_endpoint }}/apis/subresources.kubevirt.io/v1/namespaces/{{ vm_namespace }}/virtualmachines/{{ vm_name }}/addvolume"
        method: PUT
        headers:
          Authorization: "Bearer {{ lookup('env', 'K8S_AUTH_API_KEY') }}"
          Content-Type: "application/json"
        body_format: json
        body:
          name: "{{ _disk_name }}"
          disk:
            name: "{{ _disk_name }}"
            disk:
              bus: scsi
          volumeSource:
            dataVolume:
              name: "{{ _disk_name }}"
        validate_certs: "{{ lookup('env', 'K8S_AUTH_VERIFY_SSL') | default('yes', true) }}"
        status_code:
          - 200
          - 202
      register: vm_addvolume
      delegate_to: localhost
      run_once: true

    - name: Display disk attachment status
      ansible.builtin.debug:
        msg: "Disk '{{ _disk_name }}' successfully hot-plugged to VM '{{ vm_name }}'"
      when: vm_addvolume is succeeded
      delegate_to: localhost
      run_once: true

    - name: Verify disk attachment
      kubernetes.core.k8s_info:
        api_version: kubevirt.io/v1
        kind: VirtualMachine
        name: "{{ vm_name }}"
        namespace: "{{ vm_namespace }}"
      register: vm_final
      delegate_to: localhost
      run_once: true

    - name: Extract final disk configuration
      ansible.builtin.set_fact:
        final_volumes: "{{ vm_final.resources[0].spec.template.spec.volumes | default([]) }}"
        final_disks: "{{ vm_final.resources[0].spec.template.spec.domain.devices.disks | default([]) }}"
      delegate_to: localhost
      run_once: true

    - name: Verify new disk in configuration
      ansible.builtin.assert:
        that:
          - _disk_name in (final_volumes | map(attribute='name') | list)
          - _disk_name in (final_disks | map(attribute='name') | list)
        success_msg: "✓ Disk '{{ _disk_name }}' verified in VM configuration"
        fail_msg: "Disk attachment verification failed"
      delegate_to: localhost
      run_once: true

    - name: Check if VM is running
      kubernetes.core.k8s_info:
        api_version: kubevirt.io/v1
        kind: VirtualMachineInstance
        name: "{{ vm_name }}"
        namespace: "{{ vm_namespace }}"
      register: vmi_check
      delegate_to: localhost
      run_once: true

    - name: Display VM runtime status
      ansible.builtin.debug:
        msg:
          - "VM is currently running (VirtualMachineInstance exists)"
          - "The disk will be available after VM restart"
      when: vmi_check.resources | length > 0
      delegate_to: localhost
      run_once: true

    - name: Display VM offline status
      ansible.builtin.debug:
        msg:
          - "VM is currently stopped"
          - "The disk will be available when the VM starts"
      when: vmi_check.resources | length == 0
      delegate_to: localhost
      run_once: true

    - name: Display operation summary
      ansible.builtin.debug:
        msg:
          - "=========================================="
          - "Hot-Add Disk Operation Complete"
          - "=========================================="
          - "DataVolume created: {{ _disk_name }}"
          - "Disk attached to VM: {{ vm_name }}"
          - "Disk size: {{ disk_size }}"
          - "Storage class: {{ _storage_class }}"
          - "Disk bus type: {{ _disk_bus }}"
          - ""
          - "Total disks on VM: {{ final_disks | length }}"
          - ""
          - "Verification Commands:"
          - "  oc get dv {{ _disk_name }} -n {{ vm_namespace }}"
          - "  oc get vm {{ vm_name }} -n {{ vm_namespace }} -o yaml | grep -A 5 volumes"
          - "=========================================="
      delegate_to: localhost
      run_once: true
